# Generated by Django 5.2.1 on 2025-11-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesperson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='odoo_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
