# Generated by Django 5.2.1 on 2025-11-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesperson', '0002_customuser_odoo_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
